### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by caiqien** [zylele/dubbokeeper-mqs#1]
提示找不到jdbc driver，但是maven却是下载了mysql-connector6.0.6了，不知是不是版本太高不支持，哈

**Comment by zylele** [comment]
@caiqien 是的，mysql-connector6.0.6必须要jdk1.8，推荐的驱动是com.mysql.cj.jdbc.Driver，com.mysql.jdbc.Driver已经被废弃了，但是不影响启动。目测是你的jdk低于1.8。已经将mysql-connector版本改成5.x，你手动修改下版本或者拉取下最新代码即可。
